server:
    port: 8080
eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: true
        fetch-registry: true
spring:
    application:
        name: inventario-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            - id: config-service
              uri: lb://configuracion-service
              predicates:
              - Path=/usuarios/**
            - id: ingr-service
              uri: lb://ingrediente-service
              predicates:
               - Path=/ingredientes/**
            - id: plat-service
              uri: lb://plato-service
              predicates:
               - Path=/platos/**